# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: assertive

  auto_review:
    enabled: true
    base_branches:
      - "public-main"
      - "review-base"

  path_filters:
    - "!app/static/vendor/**"
