"""add job.metrics

Revision ID: bc30b366a2f4
Revises: c21e7fe5c931
Create Date: 2025-12-26 07:08:44.122274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc30b366a2f4'
down_revision = 'c21e7fe5c931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('metrics')

    # ### end Alembic commands ###
