"""add todo suggestion status

Revision ID: d1f6215c9581
Revises: 911c6c168067
Create Date: 2026-05-12 22:35:38.283332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f6215c9581'
down_revision = '911c6c168067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status in ('open', 'done')", name='ck_todo_suggestion_status'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo_suggestion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_suggestion_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_suggestion_status'))

    op.drop_table('todo_suggestion')
    # ### end Alembic commands ###
